apiVersion: apps/v1
kind: Deployment
metadata:
  name: jt-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jobtrack
  template:
    metadata:
      labels:
        app: jobtrack
    spec:
      containers:
        - name: gateway
          image: benco03/gateway:latest
          ports:
            - containerPort: 8000
        - name: job-service
          image: benco03/job-service:latest
          ports:
            - containerPort: 8001
        - name: user-service
          image: benco03/user-service:latest
          ports:
            - containerPort: 8002

---

apiVersion: v1
kind: Service
metadata:
  name: jt-service
spec:
  selector:
    app: jobtrack
  type: LoadBalancer
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 31000
      protocol: TCP
